version: '2'

services:
   jenkins:
      image: jenkins
      container_name: jenkins
      mem_limit: 1036m
      environment:
         - JAVA_OPTS=-Dhudson.model.ParametersAction.safeParameters=SVC_NAME,TAG_ID,CLUSTER_NAME,TARGET_HOST -Dhudson.model.DirectoryBrowserSupport.CSP="default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
      entrypoint: /bin/tini -- /usr/local/bin/jenkins.sh  --sessionTimeout=10080
      ports:
#      Port left for debugging
         - "8000:8080"
         - "50000:50000"
      restart: always
      logging:
         driver: json-file
         options:
            max-size: "10m"
            max-file: "4"
      volumes:
         - /opt/sfly/jenkins:/var/jenkins_home

   java-slave0:
      container_name: java-slave0
      build: java-slave/.
      logging:
         driver: json-file
         options:
            max-size: "5m"
            max-file: "4"
      ports:
         - "10020:22"
      restart: always
      privileged: true
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - /usr/bin/docker:/usr/bin/docker
         - /opt/sfly/jenkins-slave/java-slave/files/docker:/home/jenkins/.docker
         - /opt/sfly/jenkins-slave/java-slave/files/aws:/home/jenkins/.aws
         - /opt/sfly/jenkins-slave/java-slave/files/ssh:/home/jenkins/.ssh
      depends_on:
         - docker-ui

   docker-ui:
      image: portainer/portainer
      container_name: docker-ui
      mem_limit: 64m
      logging:
         driver: json-file
         options:
            max-size: "50m"
            max-file: "4"
      ports:
         - "9000:9000"
      privileged: true
      restart: always
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - /usr/local/bin/docker:/usr/bin/docker

   sonarqube:
      container_name: sonarqube
      image: sonarqube:5.6.6
      ports: 
        - "19000:9000"
        - "19092:9092"
      external_links:
         - sonardb:db
      depends_on:
         - sonardb
      mem_limit: 1048m
      logging:
         driver: json-file
         options:
            max-size: "10m"
            max-file: "2"
      environment:
         - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
         - SONARQUBE_JDBC_USERNAME=sonar
         - SONARQUBE_JDBC_PASSWORD=D07BADD0A69C41297850DCAD1B5CF7
      volumes_from:
         - plugins
      restart: always

   plugins:
      container_name: sonarqube-plugins
      image: sonarqube:5.6.6
      volumes:
       - /opt/sonarqube/extensions
       - /opt/sonarqube/lib/bundled-plugins
      command: /bin/true

   install_plugins:
      container_name: sonarqube-install-plugins
      build: sonarqube/plugins/.
      volumes_from:
         - plugins

   sonardb:
      container_name: sonarqube-sonardb
      ports:
        - 5432:5432
      image: postgres:9.5
      mem_limit: 512m
      logging:
         driver: json-file
         options:
            max-size: "10m"
            max-file: "2"
      environment:
         - POSTGRES_USER=sonar
         - POSTGRES_PASSWORD=D07BADD0A69C41297850DCAD1B5CF7
      volumes:
         - /opt/sfly/sonardb/postgres/data:/var/lib/postgresql/data

   owasp-zap:
      image: owasp/zap2docker-weekly
      container_name: owasp-zap
      mem_limit: 1036m
      entrypoint: zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
      ports:
         - "8090:8090"
      restart: always
      logging:
         driver: json-file
         options:
            max-size: "10m"
            max-file: "4"

